# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# Remove controller containers.

- name: get controller name
  set_fact:
    controller_name: "{{ name_prefix ~ host_group.index(inventory_hostname) }}"

- name: remove controller
  docker_container:
    name: "{{ controller_name }}"
    state: absent
  ignore_errors: "True"

- name: remove controller log directory
  file:
    path: "{{ whisk_logs_dir }}/{{ controller_name }}"
    state: absent
  become: "{{ logs.dir.become }}"

- name: remove controller conf directory
  file:
    path: "{{ controller.confdir }}/{{ controller_name }}"
    state: absent
  become: "{{ controller.dir.become }}"
