# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# This role will prepare target VMs for a whisk deployment using ansible.
# In deploy mode it will install all necessary packages and programs.
# In clean mode it will uninstall packages from deploy mode.

- import_tasks: deploy.yml
  when: mode == "deploy"

- import_tasks: clean.yml
  when: mode == "clean"
