# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# This role will configure and publish the CLI tarball.
# In deploy mode it will generate a new CLI config, generate a tarball and copy it to nginx.
# In clean mode it will clean the cli.nginxdir

- import_tasks: deploy.yml
  when: mode == "deploy"

- import_tasks: clean.yml
  when: mode == "clean"
