# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# This role will install a docker registry using self-signed certs.
# In deploy mode it will deploy the registry. If it pre-exists, it will be recycled.
# Recycling means retaining the last few images of all repos and importing them into the new instance.
# In clean mode it will remove the registry, deleting all images.

- import_tasks: deploy.yml
  when: mode == "deploy"

- import_tasks: clean.yml
  when: mode == "clean"
