# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# This role will install kafka in group 'kafka' in the environment inventory
# In deploy mode it will deploy kafka including zookeeper.
# In clean mode it will remove kafka and zookeeper containers.

- import_tasks: deploy.yml
  when: mode == "deploy"

- import_tasks: clean.yml
  when: mode == "clean"
