# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# Remove apigateway container.

- name: remove apigateway
  docker_container:
    name: apigateway
    state: absent
  ignore_errors: True
