# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# Recreates all views in all databases.

- include_tasks: db/recreateDoc.yml
  vars:
    dbName: "{{ db.whisk.actions }}"
    doc: "{{ lookup('file', '{{ item }}') }}"
  with_items:
    - "{{ openwhisk_home }}/ansible/files/whisks_design_document_for_entities_db_v2.1.0.json"
    - "{{ openwhisk_home }}/ansible/files/filter_design_document.json"

- include_tasks: db/recreateDoc.yml
  vars:
    dbName: "{{ db.whisk.activations }}"
    doc: "{{ lookup('file', '{{ item }}') }}"
  with_items:
    - "{{ openwhisk_home }}/ansible/files/whisks_design_document_for_activations_db_v2.1.0.json"
    - "{{ openwhisk_home }}/ansible/files/whisks_design_document_for_activations_db_filters_v2.1.0.json"
    - "{{ openwhisk_home }}/ansible/files/filter_design_document.json"
    - "{{ openwhisk_home }}/ansible/files/activations_design_document_for_activations_db.json"
    - "{{ openwhisk_home }}/ansible/files/logCleanup_design_document_for_activations_db.json"
