# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# This role will install invoker in group 'invokers' in the environment inventory
# In deploy mode it will deploy invokers.
# In clean mode it will remove the invoker containers.

- import_tasks: deploy.yml
  when: mode == "deploy"

- import_tasks: clean.yml
  when: mode == "clean"
